-- =========================================================
-- SISTEM AKUNTANSI MEMBERSHIP BILLING & PENDAPATAN GYM
-- DATABASE SUPABASE
-- =========================================================


-- =========================================================
-- 1. HAPUS TABEL LAMA
-- =========================================================

DROP TABLE IF EXISTS public.pembayaran CASCADE;
DROP TABLE IF EXISTS public.membership CASCADE;
DROP TABLE IF EXISTS public.member CASCADE;


-- =========================================================
-- 2. TABEL MEMBER
-- =========================================================

CREATE TABLE public.member (
    id_member BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nama_member VARCHAR(100) NOT NULL,

    jenis_kelamin VARCHAR(20)
        CHECK (jenis_kelamin IN ('Laki-laki', 'Perempuan')),

    no_telepon VARCHAR(20),

    email VARCHAR(100),

    alamat TEXT,

    tanggal_daftar DATE NOT NULL DEFAULT CURRENT_DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'Aktif'
        CHECK (status IN ('Aktif', 'Tidak Aktif')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- 3. TABEL MEMBERSHIP
-- =========================================================

CREATE TABLE public.membership (
    id_membership BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_member BIGINT NOT NULL,

    jenis_paket VARCHAR(50) NOT NULL
        CHECK (
            jenis_paket IN (
                'Harian',
                'Bulanan',
                '3 Bulan',
                '6 Bulan',
                'Tahunan'
            )
        ),

    tanggal_mulai DATE NOT NULL,

    tanggal_berakhir DATE NOT NULL,

    harga NUMERIC(15,2) NOT NULL DEFAULT 0
        CHECK (harga >= 0),

    status VARCHAR(20) NOT NULL DEFAULT 'Aktif'
        CHECK (
            status IN (
                'Aktif',
                'Berakhir',
                'Dibatalkan'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_membership_member
        FOREIGN KEY (id_member)
        REFERENCES public.member(id_member)
        ON DELETE CASCADE,

    CONSTRAINT tanggal_membership_valid
        CHECK (tanggal_berakhir >= tanggal_mulai)
);


-- =========================================================
-- 4. TABEL PEMBAYARAN
-- =========================================================

CREATE TABLE public.pembayaran (
    id_pembayaran BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_membership BIGINT NOT NULL,

    tanggal_pembayaran DATE NOT NULL DEFAULT CURRENT_DATE,

    periode_bayar VARCHAR(50) NOT NULL,

    jumlah_bayar NUMERIC(15,2) NOT NULL DEFAULT 0
        CHECK (jumlah_bayar >= 0),

    metode_pembayaran VARCHAR(30) NOT NULL DEFAULT 'Tunai'
        CHECK (
            metode_pembayaran IN (
                'Tunai',
                'Transfer',
                'QRIS',
                'Debit',
                'E-Wallet'
            )
        ),

    status_pembayaran VARCHAR(20) NOT NULL DEFAULT 'Lunas'
        CHECK (
            status_pembayaran IN (
                'Lunas',
                'Belum Lunas'
            )
        ),

    keterangan TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_pembayaran_membership
        FOREIGN KEY (id_membership)
        REFERENCES public.membership(id_membership)
        ON DELETE CASCADE
);


-- =========================================================
-- 5. ENABLE ROW LEVEL SECURITY
-- =========================================================

ALTER TABLE public.member ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pembayaran ENABLE ROW LEVEL SECURITY;


-- =========================================================
-- 6. POLICY MEMBER
-- =========================================================

CREATE POLICY "member_select"
ON public.member
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "member_insert"
ON public.member
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "member_update"
ON public.member
FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "member_delete"
ON public.member
FOR DELETE
TO anon, authenticated
USING (true);


-- =========================================================
-- 7. POLICY MEMBERSHIP
-- =========================================================

CREATE POLICY "membership_select"
ON public.membership
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "membership_insert"
ON public.membership
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "membership_update"
ON public.membership
FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "membership_delete"
ON public.membership
FOR DELETE
TO anon, authenticated
USING (true);


-- =========================================================
-- 8. POLICY PEMBAYARAN
-- =========================================================

CREATE POLICY "pembayaran_select"
ON public.pembayaran
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "pembayaran_insert"
ON public.pembayaran
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "pembayaran_update"
ON public.pembayaran
FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "pembayaran_delete"
ON public.pembayaran
FOR DELETE
TO anon, authenticated
USING (true);


-- =========================================================
-- 9. DATA MEMBER CONTOH
-- =========================================================

INSERT INTO public.member
(
    nama_member,
    jenis_kelamin,
    no_telepon,
    email,
    alamat,
    tanggal_daftar,
    status
)
VALUES
(
    'Andi Pratama',
    'Laki-laki',
    '081234567890',
    'andi@gmail.com',
    'Semarang',
    '2026-09-01',
    'Aktif'
),
(
    'Siti Aulia',
    'Perempuan',
    '082345678901',
    'siti@gmail.com',
    'Tembalang',
    '2026-09-03',
    'Aktif'
),
(
    'Budi Santoso',
    'Laki-laki',
    '083456789012',
    'budi@gmail.com',
    'Banyumanik',
    '2026-08-15',
    'Aktif'
);


-- =========================================================
-- 10. DATA MEMBERSHIP CONTOH
-- =========================================================

INSERT INTO public.membership
(
    id_member,
    jenis_paket,
    tanggal_mulai,
    tanggal_berakhir,
    harga,
    status
)
VALUES
(
    1,
    'Bulanan',
    '2026-09-01',
    '2026-09-30',
    250000,
    'Aktif'
),
(
    2,
    '3 Bulan',
    '2026-09-03',
    '2026-12-02',
    650000,
    'Aktif'
),
(
    3,
    'Bulanan',
    '2026-08-01',
    '2026-08-31',
    250000,
    'Berakhir'
);


-- =========================================================
-- 11. DATA PEMBAYARAN CONTOH
-- =========================================================

INSERT INTO public.pembayaran
(
    id_membership,
    tanggal_pembayaran,
    periode_bayar,
    jumlah_bayar,
    metode_pembayaran,
    status_pembayaran,
    keterangan
)
VALUES
(
    1,
    '2026-09-01',
    'September 2026',
    250000,
    'Transfer',
    'Lunas',
    'Pembayaran membership bulanan'
),
(
    2,
    '2026-09-03',
    'September - November 2026',
    650000,
    'QRIS',
    'Lunas',
    'Pembayaran paket 3 bulan'
),
(
    3,
    '2026-08-01',
    'Agustus 2026',
    250000,
    'Tunai',
    'Lunas',
    'Pembayaran membership bulanan'
);


-- =========================================================
-- 12. SELESAI
-- =========================================================

SELECT 'Database Sistem Gym berhasil dibuat!' AS pesan;